start-at-login = true

on-focused-monitor-changed = 'move-mouse monitor-lazy-center'

automatically-unhide-macos-hidden-apps = false

[mode.main.binding]
    alt-s = 'workspace s'
    alt-d = 'workspace d'
    alt-f = 'workspace f'
    alt-g = 'workspace g'
    alt-c = 'workspace c'
    alt-v = 'workspace v'
    alt-b = 'workspace b'

    alt-shift-s = ['move-node-to-workspace s', 'workspace s']
    alt-shift-d = ['move-node-to-workspace d', 'workspace d']
    alt-shift-f = ['move-node-to-workspace f', 'workspace f']
    alt-shift-g = ['move-node-to-workspace g', 'workspace g']
    alt-shift-c = ['move-node-to-workspace c', 'workspace c']
    alt-shift-v = ['move-node-to-workspace v', 'workspace v']
    alt-shift-b = ['move-node-to-workspace b', 'workspace b']

    alt-h = 'focus left'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-l = 'move right'

    alt-space = ['layout floating tiling', 'exec-and-forget open -g "rectangle://execute-action?name=center-half"']
    alt-r = 'reload-config'

